config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :projects, only: [:index, :new, :create, :edit, :update, :show, :destroy] do
    resources :tasks, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
  has_many :tasks, through: :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :projects
  
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    find_project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project.save!

    if @project.save
      redirect_to projects_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def update
    @project = current_user.projects.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    find_project
    @project.destroy!
    
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :user)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @project = current_user.projects.find(params[:project_id])
    @tasks = @project.tasks
  end

  def new
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.new(task_params)
    @task.save

    if @task.save
      redirect_to project_task_path(@project, @task)
    else
      render :new
    end
  end

  def edit
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @project = @task.project_id
    if @task.update(task_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @project = @task.project_id
    @task.destroy!
    
    redirect_to project_path(@project)
  end

  private

  def task_params
    params.require(:task).permit(:name, :text, :date, :done, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tinymce_assets %>
    <script type="text/javascript" src="/assets/tinymce.js"></script>
  </head>

  <body class='bg-light'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Tasks Manager</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Créer un projet", new_project_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mes projets", projects_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
            <%= link_to "Inscription", new_user_registration_path, class: "nav-link" %></li>
        </li>
        <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link"%></li>
        </li>
      <% end %>
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li> %>
      </ul>
    </div>
  </nav>
    <div class="container pt-5 pb-5">
      <% if notice %>
        <div class="alert alert-warning" role="alert"><%= notice %></div>
        <p class="alert"><%= alert %></p>
      <% end %>
      
      <%= yield %>
      <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>
  </body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

app/views/pages/home.html.erb
<div class="card">
  <div class="card-body">
  <h2 class='card-title d-flex justify-content-between mb-4'>Dashboard</h2>
    <% if user_signed_in? %>
      <div class="row">
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= current_user.projects.count %> projet<%= "s" if current_user.projects.count > 1 %></h5>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= current_user.tasks.count %> tâche<%= "s" if current_user.projects.count > 1 %></h5>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= current_user.tasks.where(done: false).count %> tâche<%= "s" if current_user.tasks.where(done: false).count > 1 %> en cours</h5>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= current_user.tasks.where(done: true).count %> tâche<%= "s" if current_user.tasks.where(done: true).count > 1 %> terminée<%= "s" if current_user.tasks.where(done: true).count > 1 %></h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<%= simple_form_for [@project] do |f| %>
  <%= f.input :name, placeholder: "Mon premier projet", label: "Nom du projet", class: 'mb-3' %>
  <%= f.submit value: "Modifier", class: 'btn btn-primary' %>
<% end %>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span><%= current_user.projects.count %> projet<%= "s" if current_user.projects.count > 1 %></span>
      <%= link_to "Créer un projet", new_project_path, class: 'btn btn-primary' %>
    </h2>

    <% @projects.each do |project| %>
      <% if project.user == current_user %>
        <%= link_to project, class: 'text-decoration-none' do %>
          <div class="card project-card mb-3">
            <div class="card-body pb-1">
              <h5 class='card-title text-dark'><b><%= project.name %></b></h5>
              <p class='text-secondary'><%= project.tasks.count %> tâche<%= "s" if project.tasks.count > 1 %></p>

              <%= link_to edit_project_path(project), class: 'edit-icon' do %><i class="fa fa-edit"></i><% end %>
              <%= link_to project, class: 'delete-icon', data: { confirm: 'Êtes-vous sûr de supprimer ce projet et les tâches qu\'il contient ?' }, method: :delete do%><i class="fa fa-trash"></i><% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<%= simple_form_for [@project] do |f| %>
  <div class="input-group">
    <%= f.input :name, class: 'form-control' %>
    <div class="input-group-append">
      <%= f.submit value: "Créer", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span><%= @project.name %></span>
      <%= link_to "Créer une tâche", new_project_task_path(@project), class: 'btn btn-primary' %>
    </h2>
    
    <% if (((@project.tasks.count { |x| x.done == true }) * 100) / @project.tasks.count rescue 0) > 0%>
      <div class="progress mb-4" style="height: 2em;">
        <div class="progress-bar" role="progressbar" style="width: <%= ((@project.tasks.count { |x| x.done == true }) * 100) / @project.tasks.count rescue 0 %>%;" aria-valuenow="<%= ((@project.tasks.count { |x| x.done == true }) * 100) / @project.tasks.count rescue 0 %>" aria-valuemin="0" aria-valuemax="100"><%= ((@project.tasks.count { |x| x.done == true }) * 100) / @project.tasks.count rescue 0 %>% des tâches réalisées</div>
      </div>
    <% end %>

<div class="card mb-4">
  <h5 class="card-header mb-3">Tâches en cours (<%= @project.tasks.where(done: false).count %>/<%= @project.tasks.count %>)</h5>
    <% if @project.tasks.where(done: false).count > 0 %>
      <% @project.tasks.each do |task| %>
        <% if task.done == false %>
            <div class="task-description mx-3">
              <%= simple_form_for([@project, task], remote: true, authenticity_token: true) do |f| %>
                <%= f.check_box :done, class: 'form-check-input', onchange: "form.submit();" %>
              <% end %>

              <%= link_to project_task_path(@project, task), class: 'text-decoration-none' do %>
                <div class="card">
                  <div class="card-body pb-2">
                    <h5 class='card-title text-dark'><b><%= task.name %></b></h5>
                    <p class='text'><%= strip_tags(task.text).truncate(250) %></p>

                    <%= link_to edit_project_task_path(@project, task), class: 'edit-icon' do %><i class="fa fa-edit"></i><% end %>
                    <%= link_to project_task_path(@project, task), class: 'delete-icon', data: { confirm: 'Êtes-vous sûr de supprimer cette tâche ?' }, method: :delete do%><i class="fa fa-trash"></i><% end %>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
      <% end %>
    <% elsif @project.tasks.count > 0%>
      <div class="task-description mx-3">
        Bravo ! Toutes les tâches sont terminées.
      </div>
    <% else %>
      <div class="task-description mx-3">
        Aucune tâche en cours
      </div>
    <% end %>
</div>

    
<div class="card">
  <h5 class="card-header mb-3">Tâches terminées (<%= @project.tasks.where(done: true).count %>/<%= @project.tasks.count %>)</h5>
  <% if @project.tasks.where(done: true).count > 0 %>
    <% @project.tasks.each do |task| %>
      <% if task.done %>
          <div class="task-description mx-3">
            <%= simple_form_for([@project, task], remote: true, authenticity_token: true) do |f| %>
              <%= f.check_box :done, class: 'form-check-input', onchange: "form.submit();" %>
            <% end %>

            <%= link_to project_task_path(@project, task), class: 'text-decoration-none' do %>
              <div class="card">
                <div class="card-body pb-2">
                  <h5 class='card-title text-dark'><b><%= task.name %></b></h5>
                  <p class='text'><%= strip_tags(task.text).truncate(250) %></p>

                  <%= link_to edit_project_task_path(@project, task), class: 'edit-icon' do %><i class="fa fa-edit"></i><% end %>
                  <%= link_to project_task_path(@project, task), class: 'delete-icon', data: { confirm: 'Êtes-vous sûr de supprimer cette tâche ?' }, method: :delete do%><i class="fa fa-trash"></i><% end %>
                </div>
              </div>
            <% end %>
          </div>
      <% end %>
    <% end %>
  <% else %>
      <div class="task-description mx-3">
        Aucune tâche n'est terminée.
      </div>
    <% end %>
</div>

app/views/tasks/edit.html.erb
<%= simple_form_for [@project, @task] do |f| %>
  <%= f.input :name, input_html: { class: "mb-3" }, label: "Titre de la tâche" %>
  <%= f.input :text, input_html: { class: "tinymce" }, label: false %>
  <%= tinymce %>
  <div class="mt-3">
    <%= f.input :date %>
  </div>
  <%= f.submit value: "Modifier", class: 'btn btn-primary mt-3' %>
<% end %>

app/views/tasks/new.html.erb
<%= simple_form_for [@project, @task] do |f| %>
  <%= f.input :name, input_html: {class: "mb-3" }, label: "Titre de la tâche" %>
  <%= f.input :text, input_html: {class: "tinymce" }, label: false %>
  <%= tinymce %>
  <div class="mt-3">
    <%= f.input :date %>
  </div>
  <%= f.submit value: "Créer une tâche", class: 'btn btn-primary mt-3' %>
<% end %>

app/views/tasks/show.html.erb
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'><%= @task.name %></h2
    <p><%= @task.text.html_safe %></p>
  </div>
</div>